name: Train and Deploy

on: 
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 8 * * MON-FRI'

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - id : auth
      uses: actions/checkout@v2

    - name: Setup GCP client
      uses: google-github-actions/setup-gcloud@main
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download the latest dataset
      run: |
        gsutil cp gs://automate1a/heart.csv datasets/default.csv

    - name: Run training task
      run: |
        python steps/train.py --path=datasets/default.csv

    - name: Upload new model and associated metrics
      run: |
        gsutil cp artifacts/pipeline.joblib gs://automate1-370707.appspot.com/models/latest.joblib
        gsutil cp artifacts/pipeline.joblib gs://automate1-370707.appspot.com/models/${{ env.GITHUB_RUN_ID }}.joblib
        gsutil cp artifacts/metrics.json gs://automate1-370707.appspot.com/models/metrics/${{ env.GITHUB_RUN_ID }}.joblib

    - name: Deploy model as Cloud Function
      run: | 
        gcloud functions deploy heart-disease --entry-point=predict_handler --runtime=python37 --project=${{ secrets.GCP_PROJECT_ID }} --allow-unauthenticated --trigger-http
